_data/conf.yml, assets/_scss/_variables.scss, assets/css/main.scss, general-info/scholarships.html, index.html
First round of fixes for #3. Includes contrast fixes, hiding sponsors on scholarships page since we don't have any yet, and menu styles.
=> Colour contrast improvements

_data/conf.yml, general-info/propose-a-workshop.html
see email call on the listserv from today
=> workshop proposals CFP, closes #12

prospectus/index.html
Fix date and space issue on Sponsorship page.
=> Update Sponsorship page

_data/conf.yml
Based on the listserv email from today.
=> open keynote proposals

_includes/homepage/going_on_block.html, general-info/propose-a-keynote.html, general-info/propose-a-talk.html, general-info/propose-a-workshop.html, general-info/scholarships.html
=> use through, rather than until, an event's end-date

_data/conf.yml
Note to self: update calendar reminders when I updating the site.
=> reopen keynote proposals and close voting.

_data/conf.yml, general-info/scholarships.html
1. show the one existing sponsor we have
2. add logic around the call for further sponsors & set the toggle to `true`
=> 2 changes related to diversity scholarship sponsors

prospectus/index.html
Realized the statistics on the prospectus copy needed updating. Fixed!
=> Updated Statistics on Prospectus

_data/conf.yml
@ranti Grabbed this one since I was looking at another PR!
Closes #51
=> close workshop voting

_data/conf.yml, prospectus/index.html
Signed-off-by: Mary Jinglewski <mary.jinglewski@gmail.com>
This PR updates the website to reflect that we're no longer accepting diversity scholarship sponsorship (and a small change to the prospectus).
=> Diversity Scholarship Update

_includes/homepage/pre_conference.html
via the poster-proposals show boolean
=> adds logic to toggle the proposals block visibility

_data/conf.yml, _data/examples/registration.yml, _data/registration.yml, _includes/homepage/jumbotron.html, _includes/homepage/pre_conference.html, general-info/attend.html, schedule/index.html
Waiting on receiving the final word before merging this in. I may also be adding commits to this as I go. This will close #91 when it's merged.
=> DO NOT MERGE - Registration Information

_includes/date_ordinals.html, _posts/2020-03-08-A-New-Approach-to-Old-Metadata.md, _posts/2020-03-08-A-journey-not-a-destination-towards-a-more-usercentered-library-discovery-experience.md, _posts/2020-03-08-AI-is-such-a-tool-Keeping-your-machine-learning-outputs-in-check.md, _posts/2020-03-08-Amplifying-Productivity--Joy-Lightweight-Tools--Techniques-to-Help-Teams-Improve-Collaboration--Communication.md, _posts/2020-03-08-Brace-Yourselves-the-Archives-are-Coming.md, _posts/2020-03-08-Cohort4Lib.md, _posts/2020-03-08-Cupper-and-leecher-tinman-and-shrimp-fiend-Data-science-tools-for-examining-historical-occupation-data.md, _posts/2020-03-08-Design-Sprints-for-Democratization.md, _posts/2020-03-08-Design-for-Diversity-Towards-More-Inclusive-Information-Systems.md, _posts/2020-03-08-Evaluating-Repairing-and-Enhancing-Accessible--PDFs.md, _posts/2020-03-08-Everything-is-Broken-but-by-How-Much-Exactly.md, _posts/2020-03-08-Imposter-syndrome-vulnerability-and-project-management-Leading-an-institutional-repository-migration.md, _posts/2020-03-08-Intellectual-Freedom-and-Technology.md, _posts/2020-03-08-Its-Gonna-Be-Metadata-Getting-Libraries-Archives-and-Museums-NSYNC.md, _posts/2020-03-08-Lets-Talk-Git-Investigating-and-Archiving-the-Scholarly-Git-Experience.md, _posts/2020-03-08-Migrating-clean-data-Two-stories-from-mess-to-success-.md, _posts/2020-03-08-No-Catalog-No-Queries-No-Problem-Building-a-DIY-Discovery-Service-for-the-Prelinger-Library.md, _posts/2020-03-08-On-the-Books-Jim-Crow-and-Algorithms-of-Resistance.md, _posts/2020-03-08-Picturing-the-Digitization-Ecosystem.md, _posts/2020-03-08-Plaintext-HTML-PDF-and-EPUB3-Who-wins-the-Accessibility-Games.md, _posts/2020-03-08-That-time-we-fought-off-a-Russian-bot-army-and-you-can-too.md, _posts/2020-03-08-The-Agile-Librarian-or-The-Library-Dev-Shop--Using-Agile-Methodology-to-Build-a-Digital-Library.md, _posts/2020-03-08-The-Digital-Is-Critical-Designing-Radical-Library-Systems.md, _posts/2020-03-08-The-day-before-you-start-as-a-manager.md, _posts/2020-03-08-Using-Temporal-Network-Analysis-to-Uncover-Bias-in-Collections.md, _posts/2020-03-08-Visualizing-Archival-Collections-for-Fun-and-NonProfit-Using-Google-Data-Studio.md, _posts/2020-03-08-Visualizing-Moving-Image-Archives.md, _posts/2020-03-08-Who-will-keep-it-running.md
Temporarily disabled appending 'th' in `date_ordinals.html`
=> add TBD to speaker talks, closes #101

_data/speakers.yml
Updating based on an email received from the Programming Committee back in early November.
=> update speaker bio for Jacob Shelby

schedule/index.html
up for debate what the best way to do display this information is
I do think a link to an explanation is helpful since people from
other countries may not know what DST entails
=> add note about DST to schedule page, ref #130

_data/registration.yml, general-info/attend.html, general-info/venues/hotel.html
these are all from an email thread with LPC
I don't know if there's good way to embed some of the hotel nuances in data files so I just wrote them in as HTML. We already have a precon block of info in registration.yml so it makes sense to use that here.
=> series of registration info updates

_data/conf.yml, conduct/index.html, general-info/venues/reception.html
This PR:
- comments out unused section in navigation on https://2020.code4lib.org/conduct/
- uses empty variables for community support volunteer info so logic works in template
- adds title to embedded google map for accessibility
=> CSV page fixes and google maps title

_includes/footer.html, search_data.json
=> only load search JS if we're going to use it

_data/conf.yml, _data/dinner.yml, general-info/venues/dinner.html
- Remove duplicate Nicky restaurant per #125 
- Add activity map link. 
- Adjust the condition to show the activity map only while keeping the link to registration and transportation information off.
=> Activity map, fix restaurant list, adjust conditions

assets/_scss/_schedule.scss, schedule/index.html
Should lines 34 - 38 in assets/_scss/_schedule.scss should be in a different spot? Did my best.
=> Fix schedule page headings, issue #21

_data/sponsors.yml
Signed-off-by: Mary Jinglewski <mary.jinglewski@gmail.com>
One more sponsorship update! 😄
=> Sponsors Update 2020

_data/conf.yml, general-info/venues/gaming.html, general-info/venues/index.html, general-info/venues/karaoke.html, general-info/venues/libtechwomen.html, general-info/venues/self.html
Gaming Night
LibTech Women
Karaoke
Self DIY event
=> Activated the rest of social activites per issue #115

_includes/homepage/going_on_block.html, _includes/homepage/sponsor_block.html, assets/_scss/_goingon.scss
For includes on homepage and schedule/timeline, use h2
and style as h3. Fixes #150
=> Fix issue #150

schedule/index.html
=> FIX: transition daily overview time range from hyphen to 'to'

_data/day1-menus.yml, _data/day2-menus.yml, _data/day3-menus.yml, _data/schedule.yml, schedule/food/day1-menus.html, schedule/food/day2-menus.html, schedule/food/day3-menus.html
=> Add daily menu files and update associated display controls

_data/sponsors.yml
One more Sponsorship notation! Thanks, y'all!
=> Famous Last Words
