code4lib/2020.code4lib.org

_data/conf.yml, _data/examples/schedule.yml, general-info/accessibility.html, general-info/first-timers.html
Related to #5. Pages to check:
- general-info/first-timers
- general-info/accessibility
Testing notes:
- first test as is, there should be no mention of quiet room on A11y page and no breakouts/lightning talks on First Timers
- set quiet-room.show to `true` in conf.yml & check that a) it shows up on A11y, b) it shows up in the subnav menu
- copy example/schedule.yml into the _data dir to test the First Timers page, breakouts/lightning talks should appear using links taken from those schedule events
=> work on portable year-over-year content

prospectus/index.html
see `#conference-website` Slack channel for details on this:
kathy.azevedo: "We are getting ready to launch the Sponsorship Registration site. We’ve made a few updates and need the website corrected. Can someone please make the following edits?
(1) Childcare - Change to 1 available at $2,000. Add bullet - “Signage acknowledging the sponsor”.
(2) Transportation - Change to 1 available at $2,000. Remove the following text from second bullet - “including a short message from the sponsor”.
After the site has been published, I will send the link to update the button link. Thanks!"
=> childcare & transportation updates to prospectus

_data/examples/sponsors.yml, general-info/attend.html
right now it's just the hard-coded value from 2019
testing this you'll want to try out the test data (_data/examples/sponsors.yml). Should not mention a sponsor before you put that file into _data and then look like this with test data:
=> logic for showing transcription sponsor(s)

assets/_scss/_global.scss, assets/_scss/_mixins.scss, assets/_scss/_variables.scss, assets/css/main.scss
Closes #31. Firefox didn't show a focus state, this should add one while also retaining the native focus state for Chrome & Safari. Firefox screenshot: 
Not sure why the first `outline` property is unchecked there...but you can see the effect.
To test:
- pull down changes, build site locally
- open home page in Chrome, either inspect & add `:focus` state to button or keyboard navigate to one
- do the same thing in Firefox
- (ideally) do the same thing in Edge or IE
=> fallback focus state for all .btns

general-info/propose-a-keynote.html
To test: just render the site and visit /general-info/propose-a-keynote.html (it's linked off the home page)
=> use vars in 'propose a keynote' page not text, closes #44

_includes/sponsors/logo.html, general-info/scholarships.html
fixes #67
The include/sponsors/logo.html fragment now has some context awareness, you can include it while passing a `no-annotation` boolean to disable those from displaying.
=> hide sponsor annotations on scholarships page

_includes/sponsors/group_display.html
this lets us link to e.g. https://2020.code4lib.org/sponsors/#giveaway or https://2020.code4lib.org/sponsors/#platinum
=> sponsors - anchor links for each sponsor level

_data/conf.yml, assets/js/thermometer.js, general-info/angel-fund.html, general-info/scholarships.html
to test:
- home page shouldn't mention scholarships or keynote
- gen-info / scholarships shouldn't talk about accepting application & should display Angel Fund information but without soliciting donations
=> close keynote voting, scholarship applications, & angel fund donations

_data/conf.yml
- hide 'sponsor us' button on home page
- Sponsors menu link -> sponsors not prospectus
we are still missing details & logos for some sponsors but
we are OK to make this change for now, those will trickle
in over time I imagine
=> sponsors finalized for now, closes #92

_data/conf.yml, _includes/footer.html, _includes/nav.html, _includes/talks-and-workshops-buttons.html, _layouts/day-schedule.html, schedule/timeline.html
This is a decent-sized PR that introduces some new toggles in conf.yml which let us show more information on talks, workshops, & speakers without needing to know the exact schedule.
conf.yml has three new toggles up at the top now: `have-talks`, `have-workshops`, `have-schedule`. These replace the old `program-nav-links` toggle. Currently `have-talks` is true while the other two are false. After applying the PR, I'd test these things and use `bundle exec jekyll serve --drafts` so you have a draft workshop post:
- test as is
+ Schedule main menu/footer links -> schedule/timeline, Speakers link -> /speakers/
+ button for talks displays on /schedule/timeline and on /schedule/day-1/
- activate `have-workshops`
+ now there are two buttons on /schedule/timeline and /schedule/day-1/
- copy …
=> show more program/speaker info even without schedule

_data/conf.yml, _data/registration.yml
Kathy told us that the registration/sponsorship URLs have changed because the company they worked with changed domain names. I think these are the only two places we put them but please double-check.
=> update 2 URLs, see Slack

_posts/2019-02-22-Alison-Langmead.html, _posts/2020-03-09-Alison-Macrina.html
fix keynotes pages to display talk info and speaker name/image, e.g.:
https://2020.code4lib.org/keynotes/Alison-Macrina
=> fix keynotes pages

_data/registration.yml, general-info/attend.html, prospectus/index.html
also fix one hard-coded year on the Prospectus. These changes are coming from a discussion in Slack.
=> note childcare registration end date

_includes/footer.html
Table sort functionality works on localhost, but did not function on the GitHub hosted site. I've removed an unnecessary closing tag that I missed in my editor last night, but I'd appreciate a quick review.
=> FIX: remove unnecessary end tag

general-info/venues/dinner.html
Add logic to only display icon, tooltip, and .sr-only element when venue notes are available in `dinner.yml`
=> fixes issue #126

_data/emergency.yml, conduct/index.html
This adds the emergency resources for this year but also restructures how that content works to rely on a _data/emergency.yml file. To test:
- pull down this PR, confirm that the resources display on /conduct/index.html and there are no obvious errors
- try deleting some info or adding info where it doesn't yet exist to ensure the changes work
- finally, delete the whole data file—the Emergency section and its nav menu link should disappear
=> add emergency resources, closes #128

_layouts/secondary-nav.html
Fixes a few accessibility issues with the subnav that I noticed with screenreader testing.
- add the `<nav>` element to secondary navigation
- remove `role="presentation"` on list which contains child elements that have semantic meaning
- only render the sub-navigation if it exists
=> Subnav a11y improvements

_data/scholarship-recipients.yml, assets/_scss/_global.scss, general-info/scholarships.html
Also: add Recipients secondary nav link, hide it if recipients aren't shown, proper `<dl>` structure to pass accessibility audit. To test:
- apply this PR, build the site, & visit http://127.0.0.1:4000/general-info/scholarships
- Recipients should be secondary nav item & list of people will be on the page
- page passes Chrome accessibility audit (`<dl>` can only have `<dd>` & `<dt>` children, there must be at least one `<dd>` for every `<dt>` whether or not we have a bio)
- rename or delete the _data/scholarship-recipients.yml file—now the Recipients menu item should disappear and the list of people also
=> add scholarship recipients, closes #90

general-info/attend.html
I think we should just remove this link rather than change to a different
hash tag or wait until someone has used the current year's hashtag before
linking to it. I'm open to disagreement, doesn't seem a huge deal either
way.
=> rm broken instagram link per #151

assets/_scss/_sponsors.scss
Closes #163. The usual styles for links in content sections (`section .general-info a`) was being applied to these sponsor cards on a content page, not an issue for the sponsors page itself which isn't "general-info". I couldn't find a good way to override the above rule or rewrite it so I just used `!important`—I'm open to better solutions.
=> fix sponsor card hover problem

_data/schedule.yml, _posts/2020-03-10-3D-Print-Your-Data.md, _posts/2020-03-10-A-tentative-project-of-Engatibased-Chatbot-for-reference-desk-.md, _posts/2020-03-10-Advancing-Hyku-improving-institutional-repositories-for-Green-Open-Access.md, _posts/2020-03-10-Applying-Photogrammetry-to-Library-Collections.md, _posts/2020-03-10-CCPLUS-Consortia-Collaborating-on-a-Platform-for-Library-Usage-Statistics.md, _posts/2020-03-10-Crowdsourcing-for-Metadata-Enrichment-and-Outreach-Harnessing-the-Institutional-Memory-of-the-Crowd.md, _posts/2020-03-10-Customizing-WebPac-Pro-with-Bootstrap-to-improve-user-experience.md, _posts/2020-03-10-DokuWiki-as-a-Knowledge-Base.md, _posts/2020-03-10-Drupal-7-to-Drupal-8-What-a-Long-Strange-Trip-Its-Been.md, _posts/2020-03-10-Establishing-Governance-for-Project-and-Service-Management.md, _posts/2020-03-10-Extracting-with-Style-Using-Natural-Language-Processing-to-Generate-Summaries-of-Rare-Materials.md, _posts/2020-03-10-Indexing-Shared-File-Stores-to-Mine-Folksonomy-and-Clear-ROT.md, _posts/2020-03-10-Insourcing-authority-control.md, _posts/2020-03-10-Lets-Talk-About-Contingent-Labor.md, _posts/2020-03-10-Macro-Migration-Implementing-a-CloudBased-Metadata-Microservice-with-Fedora.md, _posts/2020-03-10-Maximizing-Productivity--Expediting-Metadata-Creation-and-Cleanup-for-Electronic-Theses-and-Dissertations-at-Oklahoma-State-University.md, _posts/2020-03-10-NewspaperWorks-Its-How-Samvera-Does-Newspapers.md, _posts/2020-03-10-Open-Data-Barriers-that-Persist-at-the-Institutional-Level.md, _posts/2020-03-10-Parting-the-Metadata-Sea-a-Migration-to-Preserve-Religious-Sound.md, _posts/2020-03-10-Pythagoras-Using-Python-to-Find-Patterns-in-Music-Score-Data.md, _posts/2020-03-10-Surviving-a-postdeveloper-wasteland.md, _posts/2020-03-10-Testing-the-Usability-Scalability--Accessibility-of-a-SmallScale-Application-.md, _posts/2020-03-10-The-application-of-machine-learning-technique-at-an-academic-library-a-python-example.md, _posts/2020-03-10-There-and-Back-Again-Or-how-to-pave-your-way-to-the-Library-of-the-Future-and-still-honor-your-past.md, _posts/2020-03-10-UsinUsing-XQuery-for-Metadata-Transformations.md, _posts/2020-03-10-Whats-a-Microfilm-Proper-Digital-Archiving-for-Theses-and-Dissertations.md
This adds posters from a spreadsheet that was shared with me. A few may be subject to change/removal but we can deal with that later. To test:
- visit the day 2 schedule, find the posters link at 3:20pm
- view the posters index, test a few of them
The speakers text on these is freeform and sometimes includes institutions, positions, parentheticals. I don't think it's worth our time to clean it up and I think poster session speakers should be able to display their affiliations too so I'm fine with it.
Also, we don't know the location of the poster session yet but it can be bulk added to all the posts when we do.
=> add posters

_includes/menu.html, assets/_scss/_menu.scss
doing .h2, .h3 wasn't enough because the actual heading tag is used in SASS
so I added new classes and made the SASS work independent of the tag
also used a nested selector to clean up the SASS code a bit. This closes #178
=> fix menu header hierarchies
